### ISSUE TITLE
Social - Solo previsualización de los blogs, evitar ingresar en ellos.

### ISSUE THREAD

**Issue by pakchano** [pakchano/client-duson#11]
Respuesta:
> Esto conllevaría tocar manualmente el template y editar bases fundamentales del sistema, no sería posible de la manera en la que se quiere llevar a cabo. — Jan Park

![cambios 02-05](https://user-images.githubusercontent.com/9617583/32386968-c0307724-c0a1-11e7-9e9f-d8c180014548.jpg)

**Comment by janparkio** [comment]
Todos los blogs tienen como función ingresar, no tienen como opción cancelar su ingreso de esta manera.
