### ISSUE TITLE
Navbar - Cambiar color del menu carrito

### ISSUE THREAD

**Issue by pakchano** [pakchano/client-duson#14]
![cambios 02-08](https://user-images.githubusercontent.com/9617583/32388241-d9273ca0-c0a5-11e7-8a2d-bbec5ef5cca9.jpg)

**Comment by janparkio** [comment]
![screen shot 2017-11-15 at 2 51 05 pm](https://user-images.githubusercontent.com/9617583/32851687-6ec86f82-ca14-11e7-9822-9f6b023162b7.jpg)
Cambio realizado
