### ISSUE TITLE
Checkout - Botones naranja deben ser verdes y traducción de los elementos faltantes

### ISSUE THREAD

**Issue by pakchano** [pakchano/client-duson#15]
También traducir "Calculate shipping"

![cambios 02-09](https://user-images.githubusercontent.com/9617583/32388276-f0bba914-c0a5-11e7-87bf-7c8fe96cfe11.jpg)

**Comment by janparkio** [comment]
![screen shot 2017-11-15 at 2 51 56 pm](https://user-images.githubusercontent.com/9617583/32851717-8e124e30-ca14-11e7-928a-91d6879d24a2.jpg)
Realizado, correctamente!
