### ISSUE TITLE
Error handling - Demasiados intentos realizados

### ISSUE THREAD

**Issue by janparkio** [pakchano/client-duson#18]
> El mensaje en "demasiados intentos realizados..." creo que sería bueno aparezca luego de tres intentos al menos, y al aparecer este mensaje se bloquee el ingreso como usuario, porque me sale el mensaje de "intentelo en..." y me habilita de todas maneras, te adjunto un print.

**Comment by pakchano** [comment]
No es posible editar la cantidad de intentos, esto estaba siendo bloqueado debido al plugin para bloquear tus posteos en el área social. Eso quiere decir o dejamos sin links el área social o lo sacamos a todo el resto.

**Comment by janparkio** [comment]
Ya esta funcionando correctamente con buenos limites.
![screen shot 2017-12-18 at 2 50 42 pm](https://user-images.githubusercontent.com/9617583/34120143-5e053cee-e403-11e7-9e44-7e9b7e695c57.jpg)
instalé un nuevo tipo de bloque con 4 intentos, para bloquear 20 minutos, 4 más consecutivos luego de esa espera activa otra por 24 horas. Puede solicitar desbloqueo desde el sistema de Duson, si nos escribe, pero es muy intuitivo por que puede pedir cambiar contraseña si no desea que eso ocurra.

![screen shot 2017-12-18 at 2 46 36 pm](https://user-images.githubusercontent.com/9617583/34120164-762dd9de-e403-11e7-804b-2b52a7b9a7a0.jpg)
![screen shot 2017-12-18 at 2 46 56 pm](https://user-images.githubusercontent.com/9617583/34120169-79cb91da-e403-11e7-9552-e857620590bd.jpg)
