### ISSUE TITLE
Change the email reception from buying - After Cart

### ISSUE THREAD

**Issue by janparkio** [pakchano/client-duson#19]
> Recibí el correo de mi pedido, y me escribe de un correo "pedidos@duson.com.py", como este correo no existe, seria bueno aparezca uno donde el cliente pueda escribir en caso de dudas, preferentemente sea ventas@duson.com.py. Aprovecho sobre el punto y te consulto, los pedidos llegan a los correos alejandro@duson.com.py  y  ventas@duson.com.py  ?

**Comment by pakchano** [comment]
Los pedidos ya llegan a ventas@duson.com.py,
por el momento para ser que no se pueden agregar más de dos recipientes. Pero voy a seguir investigando

**Comment by janparkio** [comment]
El objectivo fue logrado
![screen shot 2017-12-17 at 9 08 22 pm](https://user-images.githubusercontent.com/9617583/34085401-09904670-e36f-11e7-8d44-56b1d47eb87a.jpg)
