### ISSUE TITLE
Footer - Destacar iconos de redes sociales.

### ISSUE THREAD

**Issue by pakchano** [pakchano/client-duson#3]
Pueden estar en el color original del logo o bien subirlo a la barra superior en los colores blancos, como se aprecia mejor? Buscamos un destaque mayor se aceptan sugerencias.

**Comment by janparkio** [comment]
> Destacamos los iconos de redes sociales del footer.

No me permite el template colocar los icons sociales arribo propiamente dicho.

![screen shot 2017-11-08 at 2 24 05 pm](https://user-images.githubusercontent.com/9617583/32563666-9a84a336-c490-11e7-8706-00ded2c31e2f.jpg)
Si nos permite colocarlo en la barra de sandwich una vez le hagan click.
