### ISSUE TITLE
Tienda - Etiquetas del producto cambiar a color verde tras selección

### ISSUE THREAD

**Issue by pakchano** [pakchano/client-duson#5]
Color verde pastel al no seleccionar, una vez selecciona utilizar el mismo color oscuro de la barra superior.

![etiqueta-producto-duson](https://user-images.githubusercontent.com/9617583/32385337-8d7772e2-c09c-11e7-883b-74a62cfd4b2c.jpg)

**Comment by janparkio** [comment]
Esto no es posible realizar debido a que el formato es de etiqueta no un botón de menú.
