### ISSUE TITLE
Tienda - Destacar barra de cambio de moneda

### ISSUE THREAD

**Issue by pakchano** [pakchano/client-duson#8]
> Necesito un destaque superior, pasa muy desapercibido esto es un valor agregado que ninguna competencia tiene, podemos agregar un texto “Elije tu moneda” en la parte superior del botón?

![asking-better-improvement-on-ui-ux](https://user-images.githubusercontent.com/9617583/32385798-04e278d0-c09e-11e7-8d95-4434ad5e8632.jpg)

**Comment by janparkio** [comment]
El orden es definido por el template. Por debajo de la linea horizontal si se pueden organizar los botones y demás cosas. Por encima todo es parte intrínseca del template seleccionado.
