### ISSUE TITLE
General - Agregar fondo de background a la tienda

### ISSUE THREAD

**Issue by pakchano** [pakchano/client-duson#9]
> Nos gustaría agregar un fondo, debe ser opaco, una leve textura nada más, este montaje que hago es una idea debe quedar para; la vista general de la tienda y también aplicar el fondo de la carpeta una vez que ingresa.

![cambios 02-03](https://user-images.githubusercontent.com/9617583/32386115-fc3c00e2-c09e-11e7-8de2-209fb0e94c54.jpg)

**Comment by janparkio** [comment]
![screen shot 2017-11-15 at 3 31 10 pm](https://user-images.githubusercontent.com/9617583/32853427-0b22efe2-ca1a-11e7-8605-cdea3f0b510e.jpg)
Logrado pero aparecen en todas las paginas de ahora en más con fondos blancos.
Tuve que recrear otros iconos pues me costaba crear un patron con el provisto.

La opacidad del fondo es de solo 9%
